AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Cloud Resume Challenge — serverless visitor counter backend.
  Includes DynamoDB table, Lambda function, and HTTP API Gateway.

  NOTE: S3 bucket, CloudFront distribution, ACM certificate, and Route 53
  records for the static frontend can be added here or configured manually
  through the AWS Console / separate CloudFormation stacks.

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    Architectures:
      - x86_64

Resources:

  # ── DynamoDB table that stores the visitor count ──────────────────────────
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-resume-challenge
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # ── Lambda function ────────────────────────────────────────────────────────
  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cloud-resume-visitor-counter
      CodeUri: ../backend/
      Handler: lambda_function.lambda_handler
      Description: Increments and returns the visitor count from DynamoDB.
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorCountTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCountTable
      Events:
        GetVisitors:
          Type: HttpApi
          Properties:
            ApiId: !Ref VisitorApi
            Path: /visitors
            Method: GET

  # ── HTTP API (API Gateway v2) ──────────────────────────────────────────────
  VisitorApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: HTTP API for the Cloud Resume visitor counter.
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - OPTIONS
        AllowHeaders:
          - Content-Type

Outputs:

  VisitorApiUrl:
    Description: >
      Base URL for the visitor-counter API.
      Use this value in frontend/visitor-counter.js (API_URL variable).
    Value: !Sub "https://${VisitorApi}.execute-api.${AWS::Region}.amazonaws.com/visitors"

  VisitorCountFunctionArn:
    Description: ARN of the visitor counter Lambda function.
    Value: !GetAtt VisitorCountFunction.Arn
